### ISSUE TITLE
Save data from sensors to database.

### ISSUE THREAD

**Issue by dyerlytle** [LowellObservatory/InspectorGadget#2]
This can be a mysql database or an InFluxDB.

**Comment by dyerlytle** [comment]
I'm saving the values from two temperature sensors to an InfluxDB database on astropci.  I still have much to learn about InfluxDB but the fact that it adds a date/time tag automatically is helpful.

**Comment by dyerlytle** [comment]
The MesaMon program, running at the Mesa is saving temperature information into an InfluxDB database local to the system (Tweedledum.lowell.edu).  This database will be restructured in the near future.

**Comment by astrobokonon** [comment]
Done for both the 31" and the 42", as well as the 3D printer (https://github.com/LowellObservatory/Ultimonitor) so I think this one is good to close now.  I'm just working in the infrastructure needed to replicate the data from each (disparate) database back to a central location, but that's unrelated to this.
