### ISSUE TITLE
Send some kind of message to humans when something goes wrong.

### ISSUE THREAD

**Issue by dyerlytle** [LowellObservatory/InspectorGadget#3]
This could be an email or a message on the broker (although we'll need something to listen to such broker messages).

**Comment by astrobokonon** [comment]
Now handled by the JohnnyFive helper library (https://github.com/LowellObservatory/JohnnyFive) and used for the version currently deployed to the 31" (https://github.com/LowellObservatory/Docker_Pi/tree/master/MesaTools/domeTattler).
